### ISSUE TITLE
Compatibility with other game!

### ISSUE THREAD

**Issue by MinscyBubu** [TesterTesterov/mscScriptTool#1]
Hello, thanks for the tool! I was wondering if you can make this tools compatibility with this game:

https://vndb.org/v1483

Thanks in advance!

**Comment by TesterTesterov** [comment]
Hello, I could do that. It should not be hard to do so. _But is it really incompatible?_ I though it has 1 (not 0) version of the script close to Evolimit without an additional opcodes (from Jaeger).

Can you upload me all scripts (msc) of the game and post a link here?

**Comment by MinscyBubu** [comment]
Thanks for the quick response! Yeah, i try decrypt the scripts game but the tool show me this message:

![imagen](https://user-images.githubusercontent.com/88146930/127513624-3f19a74c-b0e1-43fe-873a-899c9a7c6664.png)


Scripts:

https://drive.google.com/file/d/1ASUWTYc30QFGC8V0j0zH3R73GwRdaf6v/view?usp=sharing

thanks!

**Comment by TesterTesterov** [comment]
Actually, only version 0 scripts are encrypted, and these (I have looked it a second ago) are 1st, so you don't need to decrypt them.
_And even if it was 0 version, you'd just need to enter the key... What was it again?... 0x90 or 0xff? Well, doesn't matter, since you don't need to even decrypt this script._

Also I did test it and it seemed to be fully compatible (see image below).

**What do you need to do to work with this script?**
1. Start the tool.
2. Go to "(Dis)assebmle".
3. Choose the script file (it would be even easier if you click on "..." button.
4. Choose the text file (you may enter the relative path; for instance, if you type "test.txt", it'll be created right in the tool folder).
5. To disassemble click "Disassemble script" button, to assemble -- "Assemble script" button. There should not be issues with it.

If there are lags with assembling, just reload the tool _(why I didn't use threads while writing this tool?..)_. Oh, yes, you may want to replace "\u3000" with "  " or a Japanese spacebar. It is a common issue in my old disassembler tools _(fixed only in SLGSystem due to different command outputting system)_.

===
**Test for yourself now and write the results here.**

![image](https://user-images.githubusercontent.com/66121918/127517337-28054bf5-5489-4636-b007-8e7135fc7d12.png)

**Comment by MinscyBubu** [comment]
Oh, i see, seems like i misundertanding how to use this tool haha, thank you very much for the explanation, now it's all working!

Off topic:

I was checking your repositories, you have reversed some strange engines, just for curiosity, do you have plans to reverse YU-RIS engine? I have seen a lot of tools, but without any good results on it :(

Thanks for the support!

**Comment by TesterTesterov** [comment]
Currently not planning, but I may _bump into_ this engine sooner or later. Still I'd like to do NeXAS next _(probably only scripts, since there are good tools for it's other formats)_, but don't know, will I really pick NeXAS _(and some old engine which I called "protoNeXAS")_ or some other engine.

YU-RIS (as well as a Shiina Rio, rUGP and some other nasty engines) would take _(if I heard about them correctly)_ quite a long time to successfully reverse (maybe much longer than SLG System). And I have not much time to reverse strange engines, since it's just my hobby.

===
If there was no result with other tools, then YU-RIS should have quite a big range of versions to cover, so it would be even longer to hack.

**Comment by MinscyBubu** [comment]
I see, welp, looking forward for the next tools you will be create! Nexas will be a great addition for GIGA fans :P!

Thanks again for all your job, support and kindness!

**Comment by Cerzs** [comment]
@TesterTesterov Found this issue looking for Nexas engine. Hope you can create that tool soon! Thanks in advance! :)
